sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - '8'
env:
  - SKIP_TRAVIS_WAIT=true
before_install:
  - npm i -g npm@latest
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GH_TOKEN
  verbose: true
  on:
    branch: master
