sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.npm
notifications:
  email: false
node_js:
  - '8'
env:
  - SKIP_TRAVIS_WAIT=true
before_install:
  - npm i -g npm@latest
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
